import Head from "next/head";
import { Inter } from "next/font/google";
import React from "react";
import useAuthStore from "@/store/useAuthStore";
import { useRouter } from "next/router";
import { checkAuth } from "@/lib/checkAuth";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const isAuthenticated = useAuthStore.useIsAuthenticated();
  const logout = useAuthStore.useLogout();

  const router = useRouter();

  React.useEffect(() => {
    checkAuth();
  }, []);

  if (!isAuthenticated) {
    if (router.isReady) router.push("/login");
  }

  return (
    <>
      <Head>
        <title>Catatan Keuangan</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1 className='text-center'>Dashboard</h1>
        <button onClick={logout}>logout</button>
      </main>
    </>
  );
}
